# -*- coding: utf-8 -*-
"""Copy of Submition nlp izuddin.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pU4XkpZLA2wDQe9euWPSUtRa6YBsgRvb
"""

import pandas as pd
df = pd.read_csv('/content/amazon_cells_labelled.txt', names=['review', 'label'], sep='\t')

df.head(5)

from sklearn.model_selection import train_test_split
review = df['review'].values
y = df['label'].values
text_latih, text_test, y_latih, y_test = train_test_split(review, y, test_size=0.2)

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
 
tokenizer = Tokenizer(num_words=5000, oov_token='-')
tokenizer.fit_on_texts(text_latih) 
tokenizer.fit_on_texts(text_test)
 
sequens_latih = tokenizer.texts_to_sequences(text_latih)
sequens_test = tokenizer.texts_to_sequences(text_test)
 
padded_latih = pad_sequences(sequens_latih) 
padded_test = pad_sequences(sequens_test)

vocab_size = len(tokenizer.word_index) + 1

import tensorflow as tf
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(vocab_size, 50, input_length=30),
    tf.keras.layers.LSTM(64),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

class myCallback(tf.keras.callbacks.Callback):
  def on_epoch_end(self, epoch, logs={}):
    if(logs.get('accuracy')>0.9):
      print("\nAkurasi telah mencapai >90%!")
      self.model.stop_training = True
callbacks = myCallback()

model.fit(padded_latih, y_latih, epochs=50, 
          validation_data=(padded_test, y_test), verbose=2, callbacks=[callbacks])

"""nama : Muhammad Izuddin jundullah
username dicoding : Izuddin Jundi
Email : jundigates@gmail.com
"""